### ISSUE TITLE
Accessibilité des montres connectées

### ISSUE THREAD

**Issue by ghost** [DISIC/guide-mobile_app_conception#1]
Contrairement à ce qui est écrit, Voiceover est disponible sur la montre connectée d'Apple, il est parfaitement possible de rendre une application pour l'Apple watch accessible. C'est la cas il me semble de l'application : [TV Commande d'Orange](https://itunes.apple.com/fr/app/tvcommande-dorange/id608200581?mt=8)

> Si le support cible est une montre connectée sous Android ou sous iOS, il n'est pas possible de rendre l'application complètement accessible, car il n'y a pas de lecteur d'écran pour montre à l'heure actuelle. 

Sinon félicitations pour ces documents pour l'accessibilité mobile, beau travail !

**Comment by philippeBron** [comment]
Merci beaucoup pour votre retour et vos encouragement.
Je dois prochainement rencontrer les équipes accessibilité d'Orange. J'en profiterai pour leur poser la question.
